[package]
name = "print_bytes"
version = "0.4.2"
authors = ["dylni"]
edition = "2018"
exclude = [".*", "/rustfmt.toml", "/src/bin", "/tests"]
description = """
Print bytes as losslessly as possible
"""
repository = "https://github.com/dylni/print_bytes"
readme = "README.md"
keywords = ["bytes", "osstr", "path", "print", "windows"]
categories = ["command-line-interface", "os", "wasm"]
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
features = ["min_const_generics", "specialization"]
rustc-args = ["--cfg", "print_bytes_docs_rs"]
rustdoc-args = [
    "--cfg", "print_bytes_docs_rs",
    "--extern-html-root-url", "std=https://doc.rust-lang.org",
    "-Zunstable-options",
]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["consoleapi"] }

[dev-dependencies]
os_str_bytes = "3.0"

[features]
const_generics = []
min_const_generics = []
specialization = []
