[package]
name = "print_bytes"
version = "0.5.0"
authors = ["dylni"]
edition = "2021"
rust-version = "1.57.0"
exclude = [".*", "/rustfmt.toml", "/src/bin", "/tests"]
description = """
Print bytes as losslessly as possible
"""
repository = "https://github.com/dylni/print_bytes"
readme = "README.md"
keywords = ["bytes", "osstr", "path", "print", "windows"]
categories = ["command-line-interface", "os", "wasm"]
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "print_bytes_docs_rs"]
rustdoc-args = ["--cfg", "print_bytes_docs_rs"]

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.36", features = ["Win32_Foundation", "Win32_System_Console"] }

[dev-dependencies]
os_str_bytes = "6.0"

[features]
specialization = []
