name: build

on:
  pull_request:
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 * * FRI

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: dylni/build-actions/build@master
      with:
        nightly-features: 'os_str_bytes specialization'
    timeout-minutes: 10
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
  build-other:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: dylni/build-actions/build-other@master
      with:
        nightly-features: 'os_str_bytes specialization'
        target: ${{ matrix.target }}
        version: ${{ matrix.version }}
    timeout-minutes: 10
    strategy:
      matrix:
        target: [wasm32-unknown-unknown, wasm32-wasi]
        version: [1.63.0, stable, beta, nightly]
  test:
    needs: [build]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: dylni/build-actions/test@master
      with:
        nightly-features: 'os_str_bytes specialization'
        version: ${{ matrix.version }}
    timeout-minutes: 10
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        version: [1.63.0, stable, beta, nightly]
