name: build

on:
  pull_request:
  push:
  schedule:
  - cron: 0 0 * * FRI

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - run: cargo clippy -- -Dwarnings
    - run: cargo clippy --tests -- -Dwarnings
    - run: cargo fmt -- --check
    timeout-minutes: 5
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
  build-other:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - run: rustup install ${{ matrix.version }}
    - run: rustup default ${{ matrix.version }}
    - run: rustup component add clippy
    - run: rustup target add ${{ matrix.target }}
    - run: rm --recursive src/bin
    - run: cargo clippy --target ${{ matrix.target }} -- -Dwarnings
    timeout-minutes: 5
    strategy:
      matrix:
        target: [x86_64-unknown-redox]
        version: [1.36.0, stable, beta]
  test:
    needs: [build]
    runs-on: ${{ matrix.platform }}
    env:
      RUSTFLAGS: -Dwarnings
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - run: rustup install ${{ matrix.version }}
    - run: rustup default ${{ matrix.version }}
    - run: cargo test
    - if: matrix.version == 'nightly'
      run: cargo test --features specialization
    - if: matrix.version == 'nightly'
      run: cargo test --features 'min_const_generics specialization'
    - run: cargo test --release
    timeout-minutes: 10
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        version: [1.36.0, stable, nightly]
